#!/bin/sh
set -ue

for F in ./home/* ./home/.[^.]*; do
    FULLF=$(readlink -f $F)
    if [ -f $F -o -d $F ]; then
        ln -vsfn -t "$HOME" "$FULLF"
    else
        echo "Ignore $FULLF"
    fi
done

mkdir -p "$HOME/.config"
ln -vsfn -t "$HOME/.config" "$(readlink -f .config/starship.toml)"

mkdir -p "$HOME/bin"
which starship || ln -vsfn -t "$HOME/bin" "$(readlink -f bin/starship)"

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
fi
