#!/bin/sh
set -ue

for F in ./files/* ./files/.[^.]*; do
    FULLF=$(readlink -f $F)
    if [ -f $F -o -d $F ]; then
        ln -vsfn -t $HOME $FULLF
    else
        echo "Ignore $FULLF"
    fi
done

git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
